#pragma once
#define NO_PARENT -1
#define NUMBER_OF_PARTICIPANTS 10
#define MUTATION_OCCURENCE_PERCENTAGE 15
#define MAX_PERCENTAGE_OF_NO_IMPROVEMENT_SUCCESIVE_GENERATIONS 80
#define MAX_NUMBER_OF_GENERATIONS 150
#define BOTH_CONDITIONS 0
#define NUMBER_OF_CITIES 10
#define PERCENTAGE_CONDITION -1
#define MAX_NUMBER_CONDITION 1
#define NUMBER_OF_CHROMOSOMES 200
#define SCREEN_WIDHT 1920
#define SCREEN_HEIGHT 1080