#pragma once
#define NO_PARENT -1
#define NUMBER_OF_PARTICIPANTS 20 /// 10 dla 200 i 10 miast
#define MUTATION_OCCURENCE_PERCENTAGE 10
#define MAX_PERCENTAGE_OF_NO_IMPROVEMENT_SUCCESIVE_GENERATIONS 80
#define MAX_NUMBER_OF_GENERATIONS 150
#define NUMBER_OF_CITIES 15
#define PERCENTAGE_CONDITION 0
#define MAX_NUMBER_CONDITION 1
#define NUMBER_OF_CHROMOSOMES 500
#define SCREEN_WIDHT 1920
#define SCREEN_HEIGHT 1080
#define USE_EDGE_RECOMBINATION_CROSSOVER 1 // 0-ordered crossover 1- edge recombination crossover